name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y libncurses5 libtinfo5 cmake libffi-dev build-essential \
          python3-dev sdkmanager autoconf libtool pkg-config zlib1g-dev
          pip install --upgrade pip
          # LOCK CYTHON TO STOP THE CONSTRUCTOR ERROR
          pip install "setuptools<60.0" "Cython==0.29.33" buildozer

      - name: Build with Buildozer
        run: |
          # DONT REMOVE THIS - it fixes the wsgiref print error
          mkdir -p wsgiref
          touch wsgiref/__init__.py
          
          # Force build using the develop branch for 3.11 compatibility
          buildozer android debug
        env:
          ACCEPT_SDK_LICENSE: "yes"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OMR-Scanner-App
          path: bin/*.apk
