name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
         sudo dpkg --add-architecture i386
         sudo apt update

         sudo apt install -y \
         git zip unzip \
         openjdk-17-jdk \
         autoconf automake libtool \
         pkg-config build-essential \      
         cmake ninja-build \
         libffi-dev libssl-dev \
         zlib1g-dev \
         libncurses5 libncurses5-dev libtinfo5 \
         libc6:i386 libstdc++6:i386 zlib1g:i386 \
         patchelf python3-dev
         pip install --upgrade pip
         # LOCKED CYTHON VERSION
         pip install "setuptools<60.0" "Cython==0.29.36" buildozer

      - name: Build with Buildozer
        run: |
          # Fakes a wsgiref folder so pip doesn't try to download the broken one
          mkdir -p wsgiref
          touch wsgiref/__init__.py
          
          # Direct build command
          
          
          buildozer android debug
        env:
          ACCEPT_SDK_LICENSE: "yes"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OMR-Scanner-App
          path: bin/*.apk

