name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y libncurses5 libtinfo5 cmake libffi-dev build-essential
          pip install --upgrade pip setuptools cython

      - name: Build with Buildozer
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.11
          buildozer-cmd: buildozer android debug
          work-dir: .

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OMR-Scanner-App
          path: bin/*.apk
